// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

'use client'
import { useState } from 'react'
import { Inter } from 'next/font/google'

import { ChatList } from '@components/chat/ChatList'
import './globals.css'
import { Sidebar } from './layouts/Sidebar'
import { SidebarOverlay } from './layouts/SidebarOverlay'
import { SidebarToggle } from './layouts/SidebarToggle'

const inter = Inter({ subsets: ['latin'] })

export default function RootLayout({ children }) {
  const [isSidebarOpen, setIsSidebarOpen] = useState(true)

  const toggleSidebar = () => {
    setIsSidebarOpen(!isSidebarOpen)
  }

  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-100`}>
        <Sidebar isOpen={isSidebarOpen} toggleSidebar={toggleSidebar}>
          <ChatList />
        </Sidebar>
        <SidebarOverlay isOpen={isSidebarOpen} toggleSidebar={toggleSidebar} />
        
        {!isSidebarOpen && <SidebarToggle toggleSidebar={toggleSidebar} />}
        
        <main className={`transition-all duration-300 ease-in-out
          ${isSidebarOpen ? 'ml-64' : 'ml-0'}`}>
          <div className="min-h-screen">
            {children}
          </div>
        </main>
      </body>
    </html>
  )
}